// Folder where your MP3 files live
const MUSIC_FOLDER = "music/";

const audio = document.getElementById("audio");
const titleEl = document.getElementById("title");
const artistEl = document.getElementById("artist");
const selectorEl = document.getElementById("selector");
const coverEl = document.getElementById("cover");

let playlist = [];
let currentIndex = 0;

// --- Load song list from JSON generated by GitHub Pages Action ---
fetch("music_list.json")
    .then(res => res.json())
    .then(files => {
        playlist = shuffle(files);
        playSong();
    });

// --- Shuffle function ---
function shuffle(list) {
    for (let i = list.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [list[i], list[j]] = [list[j], list[i]];
    }
    return list;
}

// --- Play current song ---
function playSong() {
    const file = playlist[currentIndex];
    const url = MUSIC_FOLDER + file;

    audio.src = url;
    audio.play().catch(e => console.log("Autoplay blocked:", e));

    readTags(url);

    selectorEl.textContent = "Selected by: DJ AutoShuffle";
}

// --- Move to next automatically ---
audio.addEventListener("ended", () => {
    currentIndex = (currentIndex + 1) % playlist.length;
    playSong();
});

// --- Read ID3 cover + metadata ---
function readTags(url) {
    jsmediatags.read(url, {
        onSuccess: tag => {
            titleEl.textContent = tag.tags.title || url;
            artistEl.textContent = tag.tags.artist || "Unknown Artist";
            console.log("TAGS:", tag);

            if (tag.tags.picture) {
                const pic = tag.tags.picture;
                const base64 = arrayBufferToBase64(pic.data);
                coverEl.src = `data:${pic.format};base64,${base64}`;
            } else {
                coverEl.src = "placeholder.png";
            }
        },
        onError: err => {
            titleEl.textContent = url;
            artistEl.textContent = "";
            coverEl.src = "placeholder.png";
        }
    });
}

// --- Helper for cover art ---
function arrayBufferToBase64(buffer) {
    let binary = "";
    const bytes = new Uint8Array(buffer);
    for (let i = 0; i < bytes.byteLength; i++) {
        binary += String.fromCharCode(bytes[i]);
    }
    return window.btoa(binary);
}
