const audio = document.getElementById("audio");
const titleEl = document.getElementById("title");
const artistEl = document.getElementById("artist");
const selectorEl = document.getElementById("selector");
const coverEl = document.getElementById("cover");

let playlist = [];
let currentIndex = 0;

// --- Load song list from tracks.json generated by build.py ---
fetch("tracks.json")
    .then(res => res.json())
    .then(tracks => {
        playlist = shuffle(tracks);
        playSong();
    })
    .catch(e => console.error("Failed to load tracks.json:", e));

// --- Shuffle function ---
function shuffle(list) {
    for (let i = list.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [list[i], list[j]] = [list[j], list[i]];
    }
    return list;
}

// --- Play current song ---
function playSong() {
    const track = playlist[currentIndex];
    if (!track) return;

    audio.src = track.file;
    audio.play().catch(e => console.log("Autoplay blocked:", e));

    // Update display with metadata from tracks.json
    titleEl.textContent = track.title;
    artistEl.textContent = track.selectedBy || "Unknown Artist";
    selectorEl.textContent = "Selected by: " + (track.selectedBy || "DJ AutoShuffle");
    coverEl.src = track.cover;

    console.log("Now playing:", track);
}

// --- Move to next automatically ---
audio.addEventListener("ended", () => {
    currentIndex = (currentIndex + 1) % playlist.length;
    playSong();
});
